### PR TITLE
BUGFIX: Prevent CKEditor from crashing in Neos 8.2

### PR DESCRIPTION
**Pull request by crydotsnake**
Resolves: #36

### CODE REVIEW

**Comment by crydotsnake** [comment]
Also tested it with Neos 8.1. Just to be sure.

**Comment by anianweber** [comment]
Hi @crydotsnake,
thanks for your PR, we will have a look at it and will merge it shortly!

**Comment by mbiberger** [comment]
Hello @crydotsnake ,

looks good to me, but can you add also a NEOS dependency 8 in the composer.json in your PR?

best regards
Markus

**Comment by crydotsnake** [comment]
@mbiberger Done. I also added Neos 7 aswell.

**Comment by mbiberger** [comment]
@crydotsnake  Thanks 🥇  Simon for your fast support! :-)

**Comment by crydotsnake** [comment]
No problem! 🙂

**Pull request merged**
