### PR TITLE
Feature/blockstyles

### PR DESCRIPTION
**Pull request by regniets**

### CODE REVIEW

**Comment by regniets** [comment]
Needs to be tested in real-world-scenarios

**Comment by bweinzierl** [comment]
Thanks for all the work! In the backend everything works as expected. You can inject both classes in every combination into the paragraph element. Dropdowns reflect the changes and are prefilled on reload.

Only one thing i noticed when publishing to frontend:
If you use more that one class (Both Dorpdowns have a selected value) only one class is rendered in frontend. As i said in backend both classes are rendered.

My configuration:

```
TechDivision:
  CkStyles:
    BlockStyles:
      presets:
        'color':
          label: 'Color'
          options:
            'black':
              label: 'Black'
              cssClass: 'text-gray-400'
            'chrome':
              label: 'Chrome'
              cssClass: 'text-chrome-300'
            'white':
              label: 'White'
              cssClass: 'text-white'
        'size':
          label: 'Size'
          options:
            'default':
              label: 'Default'
              cssClass: 'default-text'
            'large':
              label: 'Large'
              cssClass: 'large-text'
            'medium':
              label: 'Medium'
              cssClass: 'medium-text'
            'small':
              label: 'Small'
              cssClass: 'small-text'
```

**Comment by regniets** [comment]
Hi Benno, 
Thanks for your feedback. I found another issue, so that inline-styles are put outside of block elements - which destroys the whole styling. Going to fix those and push them, will notify you when ready!

**Comment by regniets** [comment]
Hi Benno, i haven't found a way yet to fix the multiple classes issue. 
If i cannot find my way around, i will bundle a first release with a hint in Readme...

**Pull request merged**
